services:
  some-scylla:
    image: scylladb/scylla:5.2.8
    container_name: some-scylla
    ports:
      - '9042:9042'

  some-scylla2:
    image: scylladb/scylla:5.2.8
    container_name: some-scylla2
    command: --seeds=some-scylla

  some-scylla3:
    image: scylladb/scylla:5.2.8
    container_name: some-scylla3
    command: --seeds=some-scylla
